2024-10-29 18:42:35,473 INFO    MainThread:37188 [wandb_setup.py:_flush():79] Current SDK version is 0.18.5
2024-10-29 18:42:35,474 INFO    MainThread:37188 [wandb_setup.py:_flush():79] Configure stats pid to 37188
2024-10-29 18:42:35,474 INFO    MainThread:37188 [wandb_setup.py:_flush():79] Loading settings from C:\Users\gabma\.config\wandb\settings
2024-10-29 18:42:35,474 INFO    MainThread:37188 [wandb_setup.py:_flush():79] Loading settings from C:\Users\gabma\Downloads\Text2Music_Ai\wandb\settings
2024-10-29 18:42:35,474 INFO    MainThread:37188 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-10-29 18:42:35,474 INFO    MainThread:37188 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-10-29 18:42:35,474 INFO    MainThread:37188 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'training.py', 'program_abspath': 'C:\\Users\\gabma\\Downloads\\Text2Music_Ai\\training.py', 'program': 'C:\\Users\\gabma\\Downloads\\Text2Music_Ai\\training.py'}
2024-10-29 18:42:35,474 INFO    MainThread:37188 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-10-29 18:42:35,474 INFO    MainThread:37188 [wandb_setup.py:_flush():79] Applying login settings: {'mode': 'offline'}
2024-10-29 18:42:35,475 INFO    MainThread:37188 [wandb_init.py:_log_setup():534] Logging user logs to C:\Users\gabma\Downloads\Text2Music_Ai\wandb\offline-run-20241029_184235-6tmo8cle\logs\debug.log
2024-10-29 18:42:35,475 INFO    MainThread:37188 [wandb_init.py:_log_setup():535] Logging internal logs to C:\Users\gabma\Downloads\Text2Music_Ai\wandb\offline-run-20241029_184235-6tmo8cle\logs\debug-internal.log
2024-10-29 18:42:35,475 INFO    MainThread:37188 [wandb_init.py:init():621] calling init triggers
2024-10-29 18:42:35,475 INFO    MainThread:37188 [wandb_init.py:init():628] wandb.init called with sweep_config: {}
config: {'wav_folder': 'C:\\Users\\gabma\\Downloads\\Text2Music_Ai\\dataset\\wavs', 'csv_file': 'C:\\Users\\gabma\\Downloads\\Text2Music_Ai\\dataset\\metadata.csv', 'hidden_dim': 512, 'time_steps': 1000, 'beta_start': 0.0001, 'beta_end': 0.02, 'batch_size': 1, 'epochs': 50, 'learning_rate': 0.0001, 'weight_decay': 1e-06, 'num_workers': 4, 'log_interval': 10, 'checkpoint_interval': 10, 'checkpoint_dir': 'C:\\Users\\gabma\\Downloads\\Text2Music_Ai\\checkpoints', 'use_wandb': True}
2024-10-29 18:42:35,475 INFO    MainThread:37188 [wandb_init.py:init():671] starting backend
2024-10-29 18:42:35,475 INFO    MainThread:37188 [wandb_init.py:init():675] sending inform_init request
2024-10-29 18:42:35,477 INFO    MainThread:37188 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2024-10-29 18:42:35,478 INFO    MainThread:37188 [wandb_init.py:init():688] backend started and connected
2024-10-29 18:42:35,482 INFO    MainThread:37188 [wandb_init.py:init():783] updated telemetry
2024-10-29 18:42:35,483 INFO    MainThread:37188 [wandb_init.py:init():816] communicating run to backend with 90.0 second timeout
2024-10-29 18:42:35,647 INFO    MainThread:37188 [wandb_init.py:init():867] starting run threads in backend
2024-10-29 18:42:35,778 INFO    MainThread:37188 [wandb_run.py:_console_start():2463] atexit reg
2024-10-29 18:42:35,778 INFO    MainThread:37188 [wandb_run.py:_redirect():2311] redirect: wrap_raw
2024-10-29 18:42:35,778 INFO    MainThread:37188 [wandb_run.py:_redirect():2376] Wrapping output streams.
2024-10-29 18:42:35,778 INFO    MainThread:37188 [wandb_run.py:_redirect():2401] Redirects installed.
2024-10-29 18:42:35,780 INFO    MainThread:37188 [wandb_init.py:init():911] run started, returning control to user process
2024-10-29 18:42:54,348 INFO    MainThread:37188 [wandb_run.py:_finish():2158] finishing run music-diffusion/6tmo8cle
2024-10-29 18:42:54,349 INFO    MainThread:37188 [wandb_run.py:_atexit_cleanup():2426] got exitcode: 0
2024-10-29 18:42:54,349 INFO    MainThread:37188 [wandb_run.py:_restore():2408] restore
2024-10-29 18:42:54,349 INFO    MainThread:37188 [wandb_run.py:_restore():2414] restore done
